version: '3'

services:
  vamshop-api:
    image: vamshop/vamshop-api
    environment:
      - LANGUAGE=ru
    ports:
      - 3001:80
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shop
      - DB_USER=
      - DB_PASS=
    volumes:
      - ./content-on-host:/var/www/vamshop-api/public/content
    depends_on:
      - db
    restart: always

  vamshop-storefront:
    image: vamshop/vamshop-storefront
    environment:
      - LANGUAGE=ru
      - API_BASE_URL=http://vamshop-api/api/v1
      - AJAX_BASE_URL=http://vamshop-api/ajax
    ports:
      - 3000:80
    depends_on:
      - vamshop-api
    restart: always

  admin:
    image: vamshop/vamshop-dashboard
    environment:
      - LANGUAGE=ru
    ports:
      - 3002:80
    depends_on:
      - vamshop-api
    restart: always

  db:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - ./db-on-host:/data/db
    restart: always