version: '3'

services:
  vamshop-api:
    image: vamshop/vamshop-api
    ports:
      - 3001:80
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shop
      - STORE_URL=http://www.example.com
      - ADMIN_BASE_URL=http://admin.example.com
      - ASSETS_BASE_URL=http://api.example.com
    volumes:
      - ./content:/var/www/vamshop-api/public/content
    depends_on:
      - db
    restart: always

  vamshop-storefront:
    image: vamshop/vamshop-storefront
    environment:
      - API_BASE_URL=http://api.example.com/api/v1
      - AJAX_BASE_URL=http://api.example.com/ajax
    ports:
      - 3000:80
    depends_on:
      - vamshop-api
    restart: always

  vamshop-dashboard:
    image: vamshop/vamshop-dashboard
    environment:
      - API_BASE_URL=http://api.example.com/api/v1
    ports:
      - 3002:80
    depends_on:
      - vamshop-api
    restart: always

  vamshop-proxy:
    image: vamshop/vamshop-proxy
    environment:
      - DOMAIN=example.com
      - API_HOST=vamshop
      - STORE_HOST=vamshop-storefront
      - ADMIN_HOST=vamshop-dashboard
    ports:
      - 80:80
    depends_on:
      - vamshop-api
      - vamshop-storefront
      - vamshop-dashboard
    restart: always

  db:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always